library(shiny)
library(quarto)

# Define UI for the Shiny app
ui <- fluidPage(
  titlePanel("Weekly GitHub Activity Report"),
  
  mainPanel(
    # Embed the Quarto-generated HTML report
    includeHTML("activity_report.html")  # Make sure this file is generated by Quarto
  )
)

# Define server logic (optional, depending on interactivity needed)
server <- function(input, output) {
  # You can add additional logic for interactivity if needed.
}

# Run the Shiny app
shinyApp(ui = ui, server = server)
