name: Generate Weekly GitHub Contributions Report

on:
  schedule:
    - cron: "0 0 * * 0"  # This triggers every Sunday at midnight (UTC).
  workflow_dispatch:  # This allows you to trigger the workflow manually as well.

jobs:
  generate_report:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out the repository
      uses: actions/checkout@v3  # Latest version of checkout
    
    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.1'  # Adjust based on the R version you are using.
    
    - name: Install dependencies
      run: |
        install.packages(c('shiny', 'httr', 'jsonlite', 'dplyr', 'gt', 'quarto', 'rsconnect'))
    
    - name: Generate the report with Quarto
      run: |
        quarto render contributions.qmd --to html --output report.html
    
    - name: Upload the report as an artifact
      uses: actions/upload-artifact@v2.3.0  # Using specific stable release
      with:
        name: github-contributions-report
        path: report.html
