name: Weekly Report

on:
  schedule:
    - cron: '0 0 * * 0'  # Weekly schedule (Sunday at midnight)
  workflow_dispatch:

jobs:
  generate-report:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repo
      - name: Checkout repository
        uses: actions/checkout@v2

      # Install Quarto v1.6.42
      - name: Install Quarto v1.6.42
        run: |
          wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.6.42/quarto-1.6.42-linux-amd64.deb
          sudo dpkg -i quarto-1.6.42-linux-amd64.deb
          sudo apt-get update
          sudo apt-get install -f

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Install necessary Python dependencies (including yagmail)
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests yagmail  # Install yagmail and other dependencies you need

      # Install R and dependencies (for Shiny and rsconnect)
      - name: Install R
        uses: r-lib/actions/setup-r@v2

      - name: Install Quarto dependencies
        run: |
          R -e "install.packages('shiny')"
          R -e "install.packages('rsconnect')"

      # Render the report using Quarto
      - name: Render the report
        run: |
          quarto render report.qmd  # Replace 'report.qmd' with the actual file name

      # Deploy to ShinyApps.io
      - name: Deploy to ShinyApps.io
        run: |
          R -e "
            library(rsconnect);
            setAccountInfo(name = Sys.getenv('SHINYAPPS_USERNAME'),
                           token = Sys.getenv('SHINYAPPS_TOKEN'),
                           secret = Sys.getenv('SHINYAPPS_SECRET'));
            deployApp('./')  # Path to the app directory, update if needed
          "
        env:
          SHINYAPPS_USERNAME: ${{ secrets.SHINYAPPS_USERNAME }}
          SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
          SHINYAPPS_SECRET: ${{ s
