name: Weekly GitHub Activity Report

on:
  schedule:
    - cron: '0 0 * * 0'  # Runs every Sunday at midnight UTC
  workflow_dispatch:

jobs:
  generate_report:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python for emailing
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install requests yagmail

    - name: Fetch GitHub activity data
      run: |
        python fetch_activity.py

    - name: Generate Quarto report
      run: |
        quarto render report.qmd

    - name: Send email with report
      env:
        GMAIL_USER: ${{ secrets.GMAIL_USER }}
        GMAIL_PASS: ${{ secrets.GMAIL_PASS }}
      run: |
        python send_email.py
