name: Weekly Report

on:
  schedule:
    - cron: '0 0 * * 0'  # Weekly schedule (Sunday at midnight)
  workflow_dispatch:

jobs:
  generate-report:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repo
      - name: Checkout repository
        uses: actions/checkout@v2

      # Install Quarto v1.6.39
      - name: Install Quarto v1.6.39
        run: |
          wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.6.39/quarto-1.6.39-linux-amd64.deb
          sudo dpkg -i quarto-1.6.39-linux-amd64.deb
          sudo apt-get update
          sudo apt-get install -f

      # Set up Python environment (if needed)
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Install necessary Python dependencies (if needed)
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests  # Install any additional dependencies you need

      # Install R and dependencies (if needed for the Shiny app)
      - name: Install R
        uses: r-lib/actions/setup-r@v2

      # Install Quarto dependencies
      - name: Install Quarto dependencies
        run: |
          R -e "install.packages('shiny')"
          R -e "install.packages('rsconnect')"

      # Render the report using Quarto
      - name: Render the report
        run: |
          quarto render report.qmd  # Replace 'report.qmd' with the actual file name

      # Send the email (assuming you have a send_email.py file)
      - name: Send Email
        run: |
          python send_email.py
