name: Generate and Deploy Weekly GitHub Activity Report

on:
  push:
    branches:
      - main  # Trigger the action when changes are pushed to the main branch
  schedule:
    - cron: '0 0 * * 0'  # Trigger weekly on Sundays at midnight

jobs:
  generate_report_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Set the Python version you need for fetching activity

    - name: Install Python dependencies
      run: |
        pip install requests yagmail  # Install necessary Python packages

    - name: Fetch GitHub activity data
      run: |
        python fetch_activity.py  # Replace with the script to gather GitHub activity

    - name: Set up R environment
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.x'  # Ensure compatibility with your R setup

    - name: Install R packages
      run: |
        R -e "install.packages('shiny')"
        R -e "install.packages('quarto')"
        R -e "install.packages('rsconnect')"

    - name: Generate Quarto report
      run: |
        quarto render report.qmd  # Generate the report using Quarto

    - name: Set up ShinyApps.io deployment
      env:
        SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}  # GitHub Secrets for ShinyApps.io Token
        SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}  # GitHub Secrets for ShinyApps.io Secret
      run: |
        R -e "rsconnect::setAccountInfo(name='your_shinyapps_username', token=Sys.getenv('SHINYAPPS_TOKEN'), secret=Sys.getenv('SHINYAPPS_SECRET'))"
        R -e "rsconnect::deployApp('path/to/your/app')"  # Path to your Shiny app directory

    - name: Send email with report
      env:
        GMAIL_USER: ${{ secrets.GMAIL_USER }}  # GitHub Secret for Gmail Username
        GMAIL_PASS: ${{ secrets.GMAIL_PASS }}  # GitHub Secret for Gmail Password
      run: |
        python send_email.py  # This sends the email with the generated report
